REASSIGN OWNED BY "olivier.dalang" TO "postgres";



REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA data_draft_idl FROM "dh101_modelling_frontiers_role";
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA data_external FROM "dh101_modelling_frontiers_role";
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM "dh101_modelling_frontiers_role";
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA vtm FROM "dh101_modelling_frontiers_role";
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA topology FROM "dh101_modelling_frontiers_role";

REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA data_draft_idl FROM "dh101_modelling_frontiers_role";
REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA data_external FROM "dh101_modelling_frontiers_role";
REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public FROM "dh101_modelling_frontiers_role";
REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA vtm FROM "dh101_modelling_frontiers_role";
REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA topology FROM "dh101_modelling_frontiers_role";

REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA data_draft_idl FROM "dh101_modelling_frontiers_role";
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA data_external FROM "dh101_modelling_frontiers_role";
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM "dh101_modelling_frontiers_role";
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA vtm FROM "dh101_modelling_frontiers_role";
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA topology FROM "dh101_modelling_frontiers_role";

REVOKE ALL PRIVILEGES ON SCHEMA data_draft_idl FROM "dh101_modelling_frontiers_role";
REVOKE ALL PRIVILEGES ON SCHEMA data_external FROM "dh101_modelling_frontiers_role";
REVOKE ALL PRIVILEGES ON SCHEMA public FROM "dh101_modelling_frontiers_role";
REVOKE ALL PRIVILEGES ON SCHEMA vtm FROM "dh101_modelling_frontiers_role";
REVOKE ALL PRIVILEGES ON SCHEMA topology FROM "dh101_modelling_frontiers_role";



REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA data_draft_idl FROM "olivier.dalang";
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA data_external FROM "olivier.dalang";
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM "olivier.dalang";
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA vtm FROM "olivier.dalang";
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA topology FROM "olivier.dalang";

REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA data_draft_idl FROM "olivier.dalang";
REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA data_external FROM "olivier.dalang";
REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public FROM "olivier.dalang";
REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA vtm FROM "olivier.dalang";
REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA topology FROM "olivier.dalang";

REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA data_draft_idl FROM "olivier.dalang";
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA data_external FROM "olivier.dalang";
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM "olivier.dalang";
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA vtm FROM "olivier.dalang";
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA topology FROM "olivier.dalang";

REVOKE ALL PRIVILEGES ON SCHEMA data_draft_idl FROM "olivier.dalang";
REVOKE ALL PRIVILEGES ON SCHEMA data_external FROM "olivier.dalang";
REVOKE ALL PRIVILEGES ON SCHEMA public FROM "olivier.dalang";
REVOKE ALL PRIVILEGES ON SCHEMA vtm FROM "olivier.dalang";
REVOKE ALL PRIVILEGES ON SCHEMA topology FROM "olivier.dalang";




REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA data_draft_idl FROM editor_role;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA data_external FROM editor_role;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM editor_role;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA vtm FROM editor_role;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA topology FROM editor_role;

REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA data_draft_idl FROM editor_role;
REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA data_external FROM editor_role;
REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public FROM editor_role;
REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA vtm FROM editor_role;
REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA topology FROM editor_role;

REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA data_draft_idl FROM editor_role;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA data_external FROM editor_role;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM editor_role;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA vtm FROM editor_role;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA topology FROM editor_role;

REVOKE ALL PRIVILEGES ON SCHEMA data_draft_idl FROM editor_role;
REVOKE ALL PRIVILEGES ON SCHEMA data_external FROM editor_role;
REVOKE ALL PRIVILEGES ON SCHEMA public FROM editor_role;
REVOKE ALL PRIVILEGES ON SCHEMA vtm FROM editor_role;
REVOKE ALL PRIVILEGES ON SCHEMA topology FROM editor_role;



GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA data_draft_idl TO public;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA data_external TO public;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO public;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA vtm TO public;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA topology TO public;

GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA data_draft_idl TO public;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA data_external TO public;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO public;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA vtm TO public;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA topology TO public;

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA data_draft_idl TO public;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA data_external TO public;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO public;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA vtm TO public;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA topology TO public;

GRANT ALL PRIVILEGES ON SCHEMA data_draft_idl TO public;
GRANT ALL PRIVILEGES ON SCHEMA data_external TO public;
GRANT ALL PRIVILEGES ON SCHEMA public TO public;
GRANT ALL PRIVILEGES ON SCHEMA vtm TO public;
GRANT ALL PRIVILEGES ON SCHEMA topology TO public;


GRANT ALL PRIVILEGES ON SCHEMA data_draft_idl TO postgres;
GRANT ALL PRIVILEGES ON SCHEMA data_external TO postgres;
GRANT ALL PRIVILEGES ON SCHEMA public TO postgres;
GRANT ALL PRIVILEGES ON SCHEMA vtm TO postgres;
GRANT ALL PRIVILEGES ON SCHEMA topology TO postgres;


ALTER DEFAULT PRIVILEGES IN SCHEMA data_draft_idl GRANT ALL ON TABLES TO public;
ALTER DEFAULT PRIVILEGES IN SCHEMA data_external GRANT ALL ON TABLES TO public;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO public;
ALTER DEFAULT PRIVILEGES IN SCHEMA vtm GRANT ALL ON TABLES TO public;
ALTER DEFAULT PRIVILEGES IN SCHEMA topology GRANT ALL ON TABLES TO public;

ALTER DEFAULT PRIVILEGES IN SCHEMA data_draft_idl GRANT ALL ON FUNCTIONS TO public;
ALTER DEFAULT PRIVILEGES IN SCHEMA data_external GRANT ALL ON FUNCTIONS TO public;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO public;
ALTER DEFAULT PRIVILEGES IN SCHEMA vtm GRANT ALL ON FUNCTIONS TO public;
ALTER DEFAULT PRIVILEGES IN SCHEMA topology GRANT ALL ON FUNCTIONS TO public;

ALTER DEFAULT PRIVILEGES IN SCHEMA data_draft_idl GRANT ALL ON SEQUENCES TO public;
ALTER DEFAULT PRIVILEGES IN SCHEMA data_external GRANT ALL ON SEQUENCES TO public;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO public;
ALTER DEFAULT PRIVILEGES IN SCHEMA vtm GRANT ALL ON SEQUENCES TO public;
ALTER DEFAULT PRIVILEGES IN SCHEMA topology GRANT ALL ON SEQUENCES TO public;


ALTER DEFAULT PRIVILEGES IN SCHEMA data_draft_idl GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA data_external GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA vtm GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA topology GRANT ALL ON TABLES TO postgres;

ALTER DEFAULT PRIVILEGES IN SCHEMA data_draft_idl GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA data_external GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA vtm GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA topology GRANT ALL ON FUNCTIONS TO postgres;

ALTER DEFAULT PRIVILEGES IN SCHEMA data_draft_idl GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA data_external GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA vtm GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA topology GRANT ALL ON SEQUENCES TO postgres;

