DELETE FROM vtm.events;
DELETE FROM vtm.entities;
DELETE FROM vtm.entity_types;
DELETE FROM vtm.related_entities;
INSERT INTO vtm.entity_types(id,name,zindex) VALUES (0,'autogenerated',10000.0);
DELETE FROM vtm.sources;