DELETE FROM vtm.properties;
DELETE FROM vtm.properties_types;
DELETE FROM vtm.entities;
DELETE FROM vtm.entity_types;
DELETE FROM vtm.related_entities;
DELETE FROM vtm.sources;

ALTER SEQUENCE vtm.entities_id_seq RESTART;
ALTER SEQUENCE vtm.entity_types_id_seq RESTART;
ALTER SEQUENCE vtm.properties_id_seq RESTART;
ALTER SEQUENCE vtm.properties_types_id_seq RESTART;
ALTER SEQUENCE vtm.related_entities_id_seq RESTART;
ALTER SEQUENCE vtm.sources_id_seq RESTART;

INSERT INTO vtm.entity_types(id,name,zindex) VALUES (0,'autogenerated',10000.0);
INSERT INTO vtm.properties_types(id,name) VALUES (0,'geom');